--II
--câu 1

--câu 2
SELECT *
FROM SANPHAM ,KHACHHANG
GO
--câu 3
UPDATE SANPHAM SET GIA =GIA/(100/5)+GIA
WHERE NUOCSX = N'Thai Lan'
--câu 4
UPDATE SANPHAM SET GIA =GIA/(100/5)+GIA
WHERE NUOCSX = N'Trung Quoc'
--câu 5
UPDATE KHACHHANG SET LOAIKH ='VIP' 
WHERE (NGDK<cast('2011/1/1' as date) AND DOANHSO>=10000000) 
OR (NGDK>cast('2011/1/1' as date) AND DOANHSO >=2000000)
--III
--câu 1
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC'
--câu 2
SELECT MASP,TENSP
FROM  SANPHAM
WHERE DVT='CAY' OR DVT='QUYEN'
--câu 3
SELECT MASP,TENSP
FROM  SANPHAM
WHERE MASP LIKE 'B%01'
--câu 4
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC' AND GIA BETWEEN 30000 AND 40000
--câu 5
SELECT MASP,TENSP
FROM  SANPHAM
WHERE (NUOCSX='TRUNG QUOC' OR NUOCSX='THAI LAN') AND GIA BETWEEN 30000 AND 40000
--câu 6
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE NGHD='1/1/2007' OR NGHD='2/1/2007'
--câu 7
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY  NGHD ASC,TRIGIA DESC
--câu 8
SELECT A.MAKH,HOTEN
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND NGHD='1/1/2007'
--câu 9
SELECT SOHD,TRIGIA
FROM  HOADON A, NHANVIEN B
WHERE A.MANV=B.MANV AND NGHD='28/10/2006' AND HOTEN='NGUYEN VAN B' 
--câu 10
SELECT C.MASP, TENSP
FROM  HOADON A, KHACHHANG B, CTHD C, SANPHAM D
WHERE A.MAKH=B.MAKH AND A.SOHD=C.SOHD AND C.MASP=D.MASP AND
  MONTH(NGHD)=10 AND YEAR(NGHD)=2006 AND HOTEN='NGUYEN VAN A' 
--câu 11
SELECT SOHD
FROM  CTHD
WHERE MASP='BB01'OR MASP='BB02'
--câu 12
SELECT SOHD
FROM  CTHD
WHERE (MASP='BB01'OR MASP='BB02') AND SL BETWEEN 10 AND 20
--câu 13
SELECT SOHD
FROM  CTHD
WHERE SL BETWEEN 10 AND 20 AND MASP='BB01'
  AND SOHD IN (  SELECT SOHD
     FROM  CTHD
     WHERE MASP='BB02')
--câu 14
SELECT DISTINCT A.MASP,TENSP
FROM  SANPHAM A, HOADON B, CTHD C
WHERE NUOCSX='TRUNG QUOC' OR
  (B.SOHD=C.SOHD AND C.MASP=A.MASP AND NGHD='1/1/2007') 
--câu 15
SELECT MASP, TENSP
FROM  SANPHAM
WHERE MASP NOT IN ( SELECT MASP
     FROM  CTHD)