--câu 1
CREATE PROCEDURE spTangLuong
AS
BEGIN
    UPDATE NHANVIEN
    SET Luong = Luong * 1.1
END
-- câu 2
ALTER TABLE NHANVIEN ADD NgayNghiHuu DATE;
go
CREATE PROCEDURE spNghiHuu
AS 
BEGIN
    UPDATE NHANVIEN
    SET NgayNghiHuu = DATEADD(YEAR, CASE WHEN PHAI = 'Nam' THEN 60 ELSE 55 END, NGSINH)
    WHERE DATEDIFF(YEAR, NgSinh, GETDATE()) >= CASE WHEN PHAI = 'Nam' THEN 60 ELSE 55 END
END
-- câu 3:
go
CREATE PROCEDURE spXemDeAn
    @DiaDiemDeAn nvarchar(50)
AS 
BEGIN
    SELECT *
    FROM DEAN
    WHERE DDIEM_DA = @DiaDiemDeAn
END
go